### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by hannajan** [porrasm/tsoha-2019#3]
Ladattu 7.4. klo 13:58

Vertaisarvioitavana työnä on sovellus, jossa voi kirjoittaa viestejä, kommentoida niitä, sekä "peukuttaa" niitä ylös tai alas. Täytyy myöntää, että itselleni esim. Flask marshmallown tai jsonify:n käyttö ei ole tuttua, joten aivan kaikkea koodista en ymmärtänyt. Tutustuin työn tietokantakaavioon ja siinä kuvailluista käsitteistä tällä hetkellä toteutettuna: user, post ja comment. Attribuutteja on työn edetessä tullut mukaan vähän enemmän kuin tietokantakaaviossa on tällä hetkellä kuvailtuna, mutta sovelluksen tietokannan rakenne vastaa mielestäni hyvin kaaviossa esitettyä rakennetta.

En löytänyt dokumentaatiosta varsinaista listaa käyttötapauksista/user storieseista (tai ehkä en vain osannut etsiä). Tutkin näitä löytämiäni käyttötapauksia perehtymällä koodiin ja testailemalla tällä hetkellä toiminnassa olevia käyttötapauksia:
- käyttäjätunnuksen luominen
- sisäänkirjautuminen
- viestin kirjoittaminen
- viestin kommentointi
- viestien listaus
- yhden viestin ja sen kommenttien tulostus
- viestin upvote ja viestin downvote (ei vielä käytössä)

Luokissa olevat metodit ovat selkeästi ja yhdenmukaisesti nimettyjä ja kuvaavat sitä, mitä metodi tekee. Create-metodeissa on toteutettuna syötetiedon validointi. Virheviestit ovat selkeitä ja kuvailevat hyvin, mitä syötteessä on vikana niin, että peruskäyttäjänkin pitäisi ymmärtää mistä on kyse. Törmäsin vain sellaiseen bugiin sovellusta testaillessa omalla koneella, että tällä hetkellä virheviestit eivät jostain syystä näy ollenkaan tai sitten tulostuu väärä virheviesti esimerkiksi rekisteröitysessä "Username is already taken", kun yrittää luoda käyttäjätunnusta, joka on liian lyhyt, vaikka sillekin on kyllä määritelty selkesti oma virheviestinsä metodissa (niin kuin muillekin validoinneille.) 

Sovelluksen rakenne on mielestäni myös looginen. Testailemieni toimintojen tekeminen oli helppoa eikä tarvinnut etsiä tai miettiä mistä mitäkin saa tehtyä. Myös koodia lukiessa sovelluksen rakenne on selkeä ja helppo hahmottaa. Rakenne on myös järkevä: esimerkiksi tietyt viestit liittyvät juuri tiettyyn käyttäjään ja tämän käyttäjän nimimerkki tulostetaan viestin tulostuksen yhteydessä. Toinen bugi mihin törmäsin oli se, että viestin kommenttia tallentaessa tulee jostain syystä virheilmoitus, mutta kommentti on kuitenkin tallentunut tietokantaan ja tulostuu, kun sivun avaa uudelleen.

En osaa nyt välttämättä suoranaisesti mitään rakentavaa palautetta antaa itse koodista. Mukava aihe ja varmaankin sopivan haastava aihe tällä harjoitustyöllä! Käyttöliittymä on kivan näköinen. Ehkä jotain pientä viilausta dokumentaatioon voisi tehdä, kun aiemmin mainitsemani käyttötapaukset voisivat olla selkeästi esillä listattuna, sekä tietokantakaaviota päivitellä kun kerkeää :) Varmaankin sovellukseen ilmestyy jossain vaiheessa yhteenvetokyselyitä. Tilastoja esim. suosituimmista kommenteista tai omien viestien ja kommenttien määrästä voisi olla mukava lukea.

**Comment by porrasm** [comment]
Kiitos palautteesta.

Dokumentaatiota tosiaan tulisi päivittää, sillä se on hieman jäljessä työtä tällä hetkellä. Virheviestien näkyminen eri lailla sivulla johtuu siitä, ettei frontend vielä tarkasta syötettä samallal lailla kuin palvelin, joten virheviestit ovat erilaiset. Palvelimen antama virheviesti kuitenkin näkyy selaimen consolessa, mutta tämä ei tietenkään normaalille käyttäjälle ole kovinkaan avuliasta. Kommentin tallennus bugia en vielä osaa selittää, mutta tämä on työn alla.
