### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by exhibiton** [porrasm/tsoha-2019#4]
# Koodikatselmointi - ReadIt Forum

## Kommentit projektin koodista
- Koodin dokumentaatio olisi hyvä päivittää ajantasalle. Esimerkiksi [Asennusohjeet](https://github.com/porrasm/tsoha-2019/blob/master/documentation/manual.md) ovat päivettyneet, eikä niiden perusteella voi projektia ajaa. En myöskään keksinyt miten se tulisi ajaa, sillä sain errorina vain 
```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    app.run(debug=True)
  File "/Users/jesseheikkila/Downloads/tsoha-2019-master/venv/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/Users/jesseheikkila/Downloads/tsoha-2019-master/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/Users/jesseheikkila/Downloads/tsoha-2019-master/venv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/Users/jesseheikkila/Downloads/tsoha-2019-master/venv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/jesseheikkila/Downloads/tsoha-2019-master/run.py'
```
Enkä myöskään löytänyt mitään tapaa osoittaa frontend-tiedostojen API-endpointia paikallisesti tiettynn porttiin (5000), jossa python toimii.
- Dokumentaatiossa on hyvä selvittää rakenne, sillä nykyinen kansio-nimeäminen "application" ja "static" eivät selkeästi erottele API/Frontend ratkaisua.
- Javascript-projekteissa on monilla erilaisia mielipiteitä miten koodi tulisi jäsennellä. Modernissa javascript toolbeltissä on kuitenkin siirrytty pois tästä, ja koodin jäsentely jätetään [prettierille](https://prettier.io/). Suosittelenkin jatkossa sen käyttöä, ja asentamaan sen editorissa auto-savella/pre-commit hookissa päälle, joten ei tarvitse siitä huolehtia jatkossa koskaan. Tämä jäsentely auttaa muiden helppoa koodin lukemista, sillä prettier alkaa olla standardi projekteissa. Syy tähän lienee 2 vuotta vanhan boilerplaten käyttö. Suosittelen uusille React-projekteille suoraan [CRA](https://facebook.github.io/create-react-app/):n käyttöä.
- Suosittelisin poistamaan turhat "print-debuggaus" sekä console.log rivit koodista 
- Sekä backend, että frontend puolella löytyy "käyttämätöntä" eli kuollutta koodia. Nämä turhat undeclared importit/functiot on hyvä poistaa. ESLint / IDE (PyCharm/VSCode) esim osaavat hyvin näyttää mitkä ovat tällaisia [#1](https://github.com/porrasm/tsoha-2019/blob/master/static/js/components/Comment.jsx#L57) [#2](https://github.com/porrasm/tsoha-2019/blob/master/static/js/components/CommentForm.jsx#L120) [#3](https://github.com/porrasm/tsoha-2019/blob/master/application/templates/index.html) ym.
- Webpackin bundle tiedostoa ei kuulu committaa repositorioon
- react ja react-dom on jätetty `--dev`-vaatimukseksi. [Ne on hyvä lisätä ilman --dev flagia](https://github.com/facebook/create-react-app/issues/4342#issuecomment-383432122)
- Kyseinen `userReducer` on noudattanut Duck-rakennetta, joka on hyvä lyhyelle tiedostolle! Actionit on kuitenkin hyvä [Redux Best Practices](https://redux.js.org/basics/actions#actionsjs) (ja Redux itse linkkaa [tähän artikkeliin lisäksi](https://medium.com/lexical-labs-engineering/redux-best-practices-64d59775802e) määritellä erikseen, eikä Action Creatorin sisällä.
- Hyvä kun käytit `baseUrl`-muuttujaa API-osoitteen DRY:ssa. Sen voisi vielä eriyttää vaikka `constants.js` tiedostoon, josta kaikki voisivat sitä kutsua ja sielä voisit määritellä sille eri arvon development ja production ympäristöille.
- `getToken` funktio on toistettu jokaisessa API-palvelussa. Se olisi hyvä eriyttää omaan tiedostoon, esim `utils/auth-token-utils.js` tai muu vastaava.

## Dokumentaatio

Dokumentaatiota puuttuu projektista vielä. Use caset / SQL-queryt sinne sekä CREATE-lauseet kannalle olisi hyvä siirtää Database.md tiedostoon niiden .txt-tiedostosta. Asennusohjeet olisi hyvä päivittää myös nykyiseen, joka ottaa huomioon javascript-frontendin. Tämä olisi hyvä olla ajantasalla, jotta ohjelmaa olisi helpompaa testata.

## Yleispalaute

En viitsi ihan kaikkea kommentointia keskittää javascript-koodin ympärille. Siinä on selkeästi monia asioita, joissa voi parantaa, mutta se ei ole tämän kurssin päätavoite. Hienoa kuitenkin, että olet valinnut "käytännönläheisen" lähestymistavan rakentaa projektityösi. Python JSON API ja React-applikaatio on hyvä valinta tehdä käytännön projekteja, ja voi tulla useasti vastaan työelämässä. Suosittelen kuitenkin jatkossa tekemään aloitusprojektin itse tai moderneilla työkaluilla, sillä uskoisin sen ohjanneen hieman väärillä jäljille jossain projektin javascript-struktuureissa. 

Bugeja en isommin löytänyt itse tuotetta klikkaillessani läpi, siitä hyvää työtä-kehut!

**Comment by porrasm** [comment]
Kiitos palautteesta.

Frontendin parantamiseen annoit hyvin vinkkejä, mutta näitä en taida keretä enää korjata ennen deadlineä. Laitan kuitenkin muistiin nämä vinkit seuraavia projekteja varten.

En osaa sanoa minkä takia asennusohjeiden mukaan projekti ei toiminut, mutta sain äsken ainakin projektin toimimaan asennusohjeiden mukaisesti (myös toisella koneella).
